"""First try

Revision ID: 03e8c8ccc42c
Revises: 
Create Date: 2023-04-25 14:55:22.442061

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03e8c8ccc42c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resources')
    op.drop_table('posts')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posts',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('author', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('post_text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='posts_pkey')
    )
    op.create_table('resources',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('version', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('token', sa.VARCHAR(length=60), autoincrement=False, nullable=False),
    sa.Column('link', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('description_text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('sub_type', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('scope', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('direction', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('language', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('language_version', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('business_unit', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('customer', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('developer', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('alternative', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('technical_dependencies', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('logical_dependencies', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('repository_path', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('impact', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('impact_description', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('paas_pkgs', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='resources_pkey')
    )
    # ### end Alembic commands ###
